export const GET_PROJECTS = "GET_PROJECTS";
export const ADD_PROJECT_SECTIONS = "ADD_PROJECT_SECTIONS";
export const REMOVE_PROJECT_SECTIONS = "REMOVE_PROJECT_SECTIONS";
export const ADD_PROJECT = "ADD_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
export const GET_SECTIONS = "GET_SECTIONS";
