export const FETCH_SUBTASKS_REQUEST = 'FETCH_SUBTASKS_REQUEST'
export const FETCH_SUBTASKS_SUCCESS = 'FETCH_SUBTASKS_SUCCESS'
export const FETCH_SUBTASKS_FAILURE = 'FETCH_SUBTASKS_FAILURE'

export const CREATE_SUBTASK_REQUEST = 'CREATE_SUBTASK_REQUEST'
export const CREATE_SUBTASK_SUCCESS = 'CREATE_SUBTASK_SUCCESS'
export const CREATE_SUBTASK_FAILURE = 'CREATE_SUBTASK_FAILURE'

export const UPDATE_SUBTASK_REQUEST = 'UPDATE_SUBTASK_REQUEST'
export const UPDATE_SUBTASK_SUCCESS = 'UPDATE_SUBTASK_SUCCESS'
export const UPDATE_SUBTASK_FAILURE = 'UPDATE_SUBTASK_FAILURE'

export const DELETE_SUBTASK_REQUEST = 'DELETE_SUBTASK_REQUEST'
export const DELETE_SUBTASK_SUCCESS = 'DELETE_SUBTASK_SUCCESS'
export const DELETE_SUBTASK_FAILURE = 'DELETE_SUBTASK_FAILURE'